### ISSUE TITLE
Firefox で manifest.json の読み込み時に警告が出る

### ISSUE THREAD

**Issue by Tsukina-7mochi** [nitech-create/nitech-moodle-extension-40a#42]
## 事象

Firefox で拡張機能の manifest を読み込んだ際に警告が発生する

![image](https://user-images.githubusercontent.com/60507815/231697210-1aa40b67-67fb-45bd-a497-592275a17ad9.png)

## 原因

- `manifest.json` に本来存在しないフィールド (`options_ui.js`, `options_ui.css`) が存在している
  - ビルドスクリプトは `manifest.json5` の情報からビルドしているため、フィールドを追加していた

## 解決方法

1. `manifest.json` を出力する際にこれらのフィールドを取り除く
2. 存在しないフィールドを用いず html ファイルからのインポートの情報をもとにビルドする
    - html を読み込むプラグインを利用する
      -  Deno で利用できるものでよいものが見つからない

**Comment by KoCSience** [comment]
manifest.json を出力する際にこれらのフィールドを取り除く
って、これなぜ難しいんですか？
